sudo: false
language: ruby
rvm:
  - "2.4.1"
  - "2.3.4"
  - "2.2.7"
  - "2.1.10"
  - jruby-9.1.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-9.1.5.0
    - rvm: ruby-head
env:
  global:
    - TESTOPTS=-v
    - JRUBY_OPTS="--debug"
